language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

#cache:
  #directories:
    #- node_modules
    
#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "wucb"
  - git config user.email "wchb163@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${wucb}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/wucb/wucb.github.io.git